const empresa = [
  {
     "id":1,
     "nombre":"Juan",
     "gerente":{
        "id":1,
        "nombre":"Carlos"
     },
     "posicion":{
        "id":1,
        "nombre":"Contador"
     }
  },
  {
     "id":2,
     "nombre":"Pedro",
     "gerente":{
        "id":1,
        "nombre":"Carlos"
     },
     "posicion":{
        "id":1,
        "nombre":"Contador"
     }
  },
  {
     "id":3,
     "nombre":"Quique",
     "gerente":{
        "id":2,
        "nombre":"Vanesa"
     },
     "posicion":{
        "id":2,
        "nombre":"Abogado"
     }
  }
];

export default empresa;